#!/bin/bash

echo "🚀 Netlify Deployment Hazırlığı"
echo "=================================="
echo ""
echo "Dosyalar hazır! Şimdi Netlify'a yükleyin:"
echo ""
echo "YÖNTEM 1 - Manuel Upload (EN KOLAY):"
echo "1. https://app.netlify.com/drop adresine gidin"
echo "2. Şu dosyaları sürükle-bırak yapın:"
echo "   - index.html"
echo "   - owlex_embed_viewer.html"
echo "   - superset_embed_viewer.html"
echo "   - netlify.toml"
echo "3. ✅ Hazır! HTTPS otomatik aktif"
echo ""
echo "YÖNTEM 2 - GitHub ile:"
echo "1. https://app.netlify.com/ adresine gidin ve giriş yapın"
echo "2. 'Add new site' > 'Import from Git'"
echo "3. GitHub'ı bağlayın ve 'ahmetemn/superset-viewer' seçin"
echo "4. Deploy ayarları otomatik algılanacak"
echo "5. 'Deploy site' butonuna tıklayın"
echo ""
echo "🌐 Deployment sonrası URL:"
echo "   https://rastgele-isim-123.netlify.app"
echo ""
echo "Not: Netlify, GitHub Pages'ten daha hızlı ve kolaydır!"
